export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_CHARACTERS_DATA = 'SET_CHARACTERS_DATA';
export const CARD_PER_PAGE_VALUE = 'CARD_PER_PAGE_VALUE';
export const SET_DETAILS_ID = 'SET_DETAILS_ID';
export const SET_DETAILS_INFO = 'SET_DETAILS_INFO';
